# Generated by Django 4.1.5 on 2023-04-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestUserModel',
            fields=[
                ('testUserId', models.AutoField(db_column='testUserId', primary_key=True, serialize=False, unique=True)),
                ('testUserName', models.CharField(db_column='testUserName', max_length=200)),
            ],
            options={
                'db_table': 'TestUser',
            },
        ),
    ]
